-- MySQL Script generated by MySQL Workbench
-- Fri Sep 20 16:31:16 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `default_schema` ;

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `default_schema` ;
USE `default_schema` ;

-- -----------------------------------------------------
-- Table `default_schema`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`categorias` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`categorias` (
  `id_categoria` INT NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `default_schema`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`Cliente` (
  `idCliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `telefono` DECIMAL NOT NULL,
  `correoElectronico` VARCHAR(100) NULL DEFAULT NULL,
  `matricula` BIGINT NULL DEFAULT NULL,
  `CURP` VARCHAR(18) NULL DEFAULT NULL,
  `Facebook` VARCHAR(50) NULL DEFAULT NULL,
  `nombreAval` VARCHAR(100) NULL DEFAULT NULL,
  `telefonoAval` DECIMAL NULL DEFAULT NULL,
  PRIMARY KEY (`idCliente`));


-- -----------------------------------------------------
-- Table `default_schema`.`Devolucion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`Devolucion` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`Devolucion` (
  `idDevolucion` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fechaDeDevolucion` DATE NULL DEFAULT NULL,
  `dias_extra` INT(2) UNSIGNED NULL DEFAULT NULL,
  `montoCobrado` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`idDevolucion`));


-- -----------------------------------------------------
-- Table `default_schema`.`Integrante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`Integrante` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`Integrante` (
  `idIntegrante` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idPuesto` INT(1) UNSIGNED NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `contrasena` VARCHAR(30) NOT NULL DEFAULT 'admin',
  `usuario` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`idIntegrante`),
  CONSTRAINT ``
    FOREIGN KEY (`idPuesto`)
    REFERENCES `default_schema`.`Puesto` (`idPuesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `Integrante_FKIndex1` ON `default_schema`.`Integrante` (`idPuesto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `default_schema`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`Producto` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`Producto` (
  `idProducto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `costo` INT NOT NULL DEFAULT 0,
  `cantidad` INT NULL DEFAULT 0,
  `rutaDeImagen` VARCHAR(100) NULL DEFAULT NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  CONSTRAINT `fk_Producto_category1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `default_schema`.`categorias` (`id_categoria`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);

CREATE INDEX `fk_Producto_category1_idx` ON `default_schema`.`Producto` (`id_categoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `default_schema`.`Renta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`Renta` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`Renta` (
  `idRenta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Devolucion_idDevolucion` INT UNSIGNED NOT NULL,
  `idCliente` INT UNSIGNED NOT NULL,
  `idIntegrante` INT UNSIGNED NOT NULL,
  `fecha` DATE NOT NULL,
  `fechaDevolucionAcordada` DATE NOT NULL,
  `montoAcordado` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idRenta`),
  CONSTRAINT ``
    FOREIGN KEY (`idIntegrante`)
    REFERENCES `default_schema`.`Integrante` (`idIntegrante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT ``
    FOREIGN KEY (`idCliente`)
    REFERENCES `default_schema`.`Cliente` (`idCliente`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT ``
    FOREIGN KEY (`Devolucion_idDevolucion`)
    REFERENCES `default_schema`.`Devolucion` (`idDevolucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `Renta_FKIndex1` ON `default_schema`.`Renta` (`idIntegrante` ASC) VISIBLE;

CREATE INDEX `Renta_FKIndex2` ON `default_schema`.`Renta` (`idCliente` ASC) VISIBLE;

CREATE INDEX `Renta_FKIndex3` ON `default_schema`.`Renta` (`Devolucion_idDevolucion` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `default_schema`.`RentaDetalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`RentaDetalle` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`RentaDetalle` (
  `idRentaDetalle` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idRenta` INT UNSIGNED NOT NULL,
  `idProducto` INT UNSIGNED NOT NULL,
  `cantidad` INT UNSIGNED NULL DEFAULT NULL,
  `importe` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`idRentaDetalle`),
  CONSTRAINT ``
    FOREIGN KEY (`idProducto`)
    REFERENCES `default_schema`.`Producto` (`idProducto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT ``
    FOREIGN KEY (`idRenta`)
    REFERENCES `default_schema`.`Renta` (`idRenta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX `RentaDetalle_FKIndex1` ON `default_schema`.`RentaDetalle` (`idProducto` ASC) VISIBLE;

CREATE INDEX `RentaDetalle_FKIndex2` ON `default_schema`.`RentaDetalle` (`idRenta` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `default_schema`.`Venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`Venta` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`Venta` (
  `idVenta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idCliente` INT UNSIGNED NOT NULL,
  `idIntegrante` INT UNSIGNED NOT NULL,
  `fecha` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `monto_total` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`idVenta`),
  CONSTRAINT ``
    FOREIGN KEY (`idIntegrante`)
    REFERENCES `default_schema`.`Integrante` (`idIntegrante`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT ``
    FOREIGN KEY (`idCliente`)
    REFERENCES `default_schema`.`Cliente` (`idCliente`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);

CREATE INDEX `Venta_FKIndex1` ON `default_schema`.`Venta` (`idIntegrante` ASC) VISIBLE;

CREATE INDEX `Venta_FKIndex2` ON `default_schema`.`Venta` (`idCliente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `default_schema`.`VentaDetalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`VentaDetalle` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`VentaDetalle` (
  `idVentaDetalle` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idVenta` INT UNSIGNED NOT NULL,
  `idProducto` INT UNSIGNED NOT NULL,
  `cantidad` INT UNSIGNED NOT NULL,
  `importe` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`idVentaDetalle`),
  CONSTRAINT ``
    FOREIGN KEY (`idVenta`)
    REFERENCES `default_schema`.`Venta` (`idVenta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT ``
    FOREIGN KEY (`idProducto`)
    REFERENCES `default_schema`.`Producto` (`idProducto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);

CREATE INDEX `VentaDetalle_FKIndex1` ON `default_schema`.`VentaDetalle` (`idVenta` ASC) VISIBLE;

CREATE INDEX `VentaDetalle_FKIndex2` ON `default_schema`.`VentaDetalle` (`idProducto` ASC) VISIBLE;

USE `default_schema` ;

-- -----------------------------------------------------
-- Placeholder table for view `default_schema`.`VistaVentasDetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_schema`.`VistaVentasDetalle` (`Cantidad` INT, `NombreProducto` INT, `ImporteUnitario` INT, `Importe` INT, `Fecha` INT);

-- -----------------------------------------------------
-- View `default_schema`.`VistaVentasDetalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`VistaVentasDetalle`;
DROP VIEW IF EXISTS `default_schema`.`VistaVentasDetalle` ;
USE `default_schema`;
CREATE  OR REPLACE VIEW `VistaVentasDetalle` AS
 SELECT vd.cantidad as Cantidad,		 
 	P.nombre as NombreProducto, 		 	
 	p.costo as ImporteUnitario, 		
 	vd.importe as Importe, 		 
 	v.fecha as Fecha 	
 	FROM Producto P, VentaDetalle vd, venta v	
 	WHERE (vd.idVenta = v.idVenta) and 		
 	(vd.idProducto = p.idProducto);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
