-- MySQL Script generated by MySQL Workbench
-- Mon Oct  7 20:15:24 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `default_schema` ;
USE `default_schema` ;

-- -----------------------------------------------------
-- Table `default_schema`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_schema`.`categorias` (
  `id_categoria` INT NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `default_schema`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_schema`.`Producto` (
  `idProducto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `costo_venta` INT NOT NULL DEFAULT 0,
  `costo_renta` INT NULL DEFAULT 10,
  `cantidad` INT NULL DEFAULT 0,
  `rutaDeImagen` VARCHAR(100) NULL DEFAULT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT 'No se proporcionó una descripción.',
  `categorias_id_categoria` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_Producto_categorias1_idx` (`categorias_id_categoria` ASC),
  CONSTRAINT `fk_Producto_categorias1`
    FOREIGN KEY (`categorias_id_categoria`)
    REFERENCES `default_schema`.`categorias` (`id_categoria`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `default_schema`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_schema`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `telefono` DECIMAL NOT NULL,
  `correoElectronico` VARCHAR(100) NULL DEFAULT NULL,
  `matricula` BIGINT NULL DEFAULT NULL,
  `CURP` VARCHAR(18) NULL DEFAULT NULL,
  `Facebook` VARCHAR(50) NULL DEFAULT NULL,
  `nombreAval` VARCHAR(100) NULL DEFAULT NULL,
  `telefonoAval` DECIMAL NULL DEFAULT NULL,
  PRIMARY KEY (`idCliente`));


-- -----------------------------------------------------
-- Table `default_schema`.`Puesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_schema`.`Puesto` (
  `idPuesto` INT NOT NULL,
  `nombrePuesto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPuesto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `default_schema`.`Integrante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_schema`.`Integrante` (
  `idIntegrante` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `contrasena` VARCHAR(30) NOT NULL DEFAULT 'admin',
  `usuario` VARCHAR(14) NOT NULL,
  `Puesto_idPuesto` INT NOT NULL,
  PRIMARY KEY (`idIntegrante`),
  INDEX `fk_Integrante_Puesto1_idx` (`Puesto_idPuesto` ASC),
  CONSTRAINT `fk_Integrante_Puesto1`
    FOREIGN KEY (`Puesto_idPuesto`)
    REFERENCES `default_schema`.`Puesto` (`idPuesto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `default_schema`.`Renta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_schema`.`Renta` (
  `idRenta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `fechaDevolucionAcordada` DATE NOT NULL,
  `montoAcordado` INT UNSIGNED NOT NULL,
  `Integrante_idIntegrante` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idRenta`),
  INDEX `fk_Renta_Integrante_idx` (`Integrante_idIntegrante` ASC),
  INDEX `fk_Renta_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_Renta_Integrante`
    FOREIGN KEY (`Integrante_idIntegrante`)
    REFERENCES `default_schema`.`Integrante` (`idIntegrante`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Renta_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `default_schema`.`Cliente` (`idCliente`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `default_schema`.`Devolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_schema`.`Devolucion` (
  `idDevolucion` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fechaDeDevolucion` DATE NULL DEFAULT NULL,
  `dias_extra` INT(2) UNSIGNED NULL DEFAULT NULL,
  `montoCobrado` INT UNSIGNED NULL DEFAULT NULL,
  `Observaciones` VARCHAR(255) NULL,
  `Renta_idRenta` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idDevolucion`),
  INDEX `fk_Devolucion_Renta1_idx` (`Renta_idRenta` ASC),
  CONSTRAINT `fk_Devolucion_Renta1`
    FOREIGN KEY (`Renta_idRenta`)
    REFERENCES `default_schema`.`Renta` (`idRenta`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `default_schema`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_schema`.`Venta` (
  `idVenta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `monto_total` INT UNSIGNED NOT NULL DEFAULT 0,
  `Cliente_idCliente` INT NOT NULL,
  `Integrante_idIntegrante` INT NOT NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `fk_Venta_Cliente1_idx` (`Cliente_idCliente` ASC),
  INDEX `fk_Venta_Integrante1_idx` (`Integrante_idIntegrante` ASC),
  CONSTRAINT `fk_Venta_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `default_schema`.`Cliente` (`idCliente`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Venta_Integrante1`
    FOREIGN KEY (`Integrante_idIntegrante`)
    REFERENCES `default_schema`.`Integrante` (`idIntegrante`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `default_schema`.`VentaDetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_schema`.`VentaDetalle` (
  `idVentaDetalle` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cantidad` INT UNSIGNED NOT NULL,
  `importe` INT UNSIGNED NULL DEFAULT NULL,
  `Venta_idVenta` INT UNSIGNED NOT NULL,
  `Producto_idProducto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idVentaDetalle`),
  INDEX `fk_VentaDetalle_Venta1_idx` (`Venta_idVenta` ASC),
  INDEX `fk_VentaDetalle_Producto1_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_VentaDetalle_Venta1`
    FOREIGN KEY (`Venta_idVenta`)
    REFERENCES `default_schema`.`Venta` (`idVenta`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_VentaDetalle_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `default_schema`.`Producto` (`idProducto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `default_schema`.`RentaDetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_schema`.`RentaDetalle` (
  `idRentaDetalle` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cantidad` INT UNSIGNED NULL DEFAULT NULL,
  `importe` INT NULL,
  `Renta_idRenta` INT UNSIGNED NOT NULL,
  `Producto_idProducto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idRentaDetalle`),
  INDEX `fk_RentaDetalle_Renta1_idx` (`Renta_idRenta` ASC),
  INDEX `fk_RentaDetalle_Producto1_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_RentaDetalle_Renta1`
    FOREIGN KEY (`Renta_idRenta`)
    REFERENCES `default_schema`.`Renta` (`idRenta`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_RentaDetalle_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `default_schema`.`Producto` (`idProducto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
