-- MySQL Script generated by MySQL Workbench
-- Thu Oct 10 14:17:20 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `default_schema` ;
USE `default_schema` ;

-- -----------------------------------------------------
-- Table `default_schema`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `default_schema`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`Producto` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`Producto` (
  `idProducto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `costoVenta` INT NOT NULL DEFAULT 0,
  `costoRenta` INT NULL DEFAULT 10,
  `cantidad` INT NULL DEFAULT 0,
  `rutaDeImagen` VARCHAR(100) NULL DEFAULT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT 'No se proporcionó una descripción.',
  `idCategoria` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_Producto_categorias1_idx` (`idCategoria` ASC),
  CONSTRAINT `fk_Producto_categorias1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `default_schema`.`Categoria` (`idCategoria`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `default_schema`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `telefono` DECIMAL NOT NULL,
  `correoElectronico` VARCHAR(100) NULL DEFAULT NULL,
  `matricula` BIGINT NULL DEFAULT NULL,
  `CURP` VARCHAR(18) NULL DEFAULT NULL,
  `Facebook` VARCHAR(50) NULL DEFAULT NULL,
  `nombreAval` VARCHAR(100) NULL DEFAULT NULL,
  `telefonoAval` DECIMAL NULL DEFAULT NULL,
  PRIMARY KEY (`idCliente`));


-- -----------------------------------------------------
-- Table `default_schema`.`Puesto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`Puesto` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`Puesto` (
  `idPuesto` INT NOT NULL,
  `nombrePuesto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPuesto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `default_schema`.`Integrante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`Integrante` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`Integrante` (
  `idIntegrante` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `contrasena` VARCHAR(30) NOT NULL DEFAULT 'admin',
  `usuario` VARCHAR(14) NOT NULL,
  `idPuesto` INT NOT NULL,
  PRIMARY KEY (`idIntegrante`),
  INDEX `fk_Integrante_Puesto1_idx` (`idPuesto` ASC),
  CONSTRAINT `fk_Integrante_Puesto1`
    FOREIGN KEY (`idPuesto`)
    REFERENCES `default_schema`.`Puesto` (`idPuesto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `default_schema`.`Renta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`Renta` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`Renta` (
  `idRenta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `fechaDevolucionAcordada` DATE NOT NULL,
  `montoAcordado` INT UNSIGNED NOT NULL,
  `idIntegrante` INT NOT NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idRenta`),
  INDEX `fk_Renta_Integrante_idx` (`idIntegrante` ASC),
  INDEX `fk_Renta_Cliente1_idx` (`idCliente` ASC),
  CONSTRAINT `fk_Renta_Integrante`
    FOREIGN KEY (`idIntegrante`)
    REFERENCES `default_schema`.`Integrante` (`idIntegrante`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Renta_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `default_schema`.`Cliente` (`idCliente`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `default_schema`.`Devolucion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`Devolucion` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`Devolucion` (
  `idDevolucion` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fechaDeDevolucion` DATE NULL DEFAULT NULL,
  `diasExtra` INT(2) UNSIGNED NULL DEFAULT NULL,
  `montoCobrado` INT UNSIGNED NULL DEFAULT NULL,
  `Observaciones` VARCHAR(255) NULL,
  `idRenta` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idDevolucion`),
  INDEX `fk_Devolucion_Renta1_idx` (`idRenta` ASC),
  CONSTRAINT `fk_Devolucion_Renta1`
    FOREIGN KEY (`idRenta`)
    REFERENCES `default_schema`.`Renta` (`idRenta`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `default_schema`.`Venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`Venta` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`Venta` (
  `idVenta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `montoTotal` INT UNSIGNED NOT NULL DEFAULT 0,
  `idCliente` INT NOT NULL,
  `idIntegrante` INT NOT NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `fk_Venta_Cliente1_idx` (`idCliente` ASC),
  INDEX `fk_Venta_Integrante1_idx` (`idIntegrante` ASC),
  CONSTRAINT `fk_Venta_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `default_schema`.`Cliente` (`idCliente`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Venta_Integrante1`
    FOREIGN KEY (`idIntegrante`)
    REFERENCES `default_schema`.`Integrante` (`idIntegrante`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `default_schema`.`VentaDetalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`VentaDetalle` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`VentaDetalle` (
  `idVentaDetalle` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cantidad` INT UNSIGNED NOT NULL,
  `importe` INT UNSIGNED NULL DEFAULT NULL,
  `idVenta` INT UNSIGNED NOT NULL,
  `idProducto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idVentaDetalle`),
  INDEX `fk_VentaDetalle_Venta1_idx` (`idVenta` ASC),
  INDEX `fk_VentaDetalle_Producto1_idx` (`idProducto` ASC),
  CONSTRAINT `fk_VentaDetalle_Venta1`
    FOREIGN KEY (`idVenta`)
    REFERENCES `default_schema`.`Venta` (`idVenta`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_VentaDetalle_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `default_schema`.`Producto` (`idProducto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `default_schema`.`RentaDetalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`RentaDetalle` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`RentaDetalle` (
  `idRentaDetalle` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cantidad` INT UNSIGNED NULL DEFAULT NULL,
  `importe` INT NULL,
  `idRenta` INT UNSIGNED NOT NULL,
  `idProducto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idRentaDetalle`),
  INDEX `fk_RentaDetalle_Renta1_idx` (`idRenta` ASC),
  INDEX `fk_RentaDetalle_Producto1_idx` (`idProducto` ASC),
  CONSTRAINT `fk_RentaDetalle_Renta1`
    FOREIGN KEY (`idRenta`)
    REFERENCES `default_schema`.`Renta` (`idRenta`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_RentaDetalle_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `default_schema`.`Producto` (`idProducto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);

USE `default_schema` ;

-- -----------------------------------------------------
-- View `default_schema`.`VistaVentasDetalle`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `default_schema`.`VistaVentasDetalle` ;
USE `default_schema`;
CREATE  OR REPLACE VIEW `VistaVentasDetalle` AS
 SELECT vd.cantidad as Cantidad,		 
 	p.nombre as NombreProducto, 		 	
 	p.costoVenta as ImporteUnitario, 		
 	vd.importe as Importe, 		 
 	v.fecha as Fecha 	
 	FROM Producto p, VentaDetalle vd, venta v	
 	WHERE (vd.idVenta = v.idVenta) and 		
 	(vd.idProducto = p.idProducto);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
